# Generated by Django 5.2.8 on 2025-11-06 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_sender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailrecord',
            name='bcc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailrecord',
            name='cc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailrecord',
            name='status',
            field=models.CharField(default='sent', max_length=20),
        ),
        migrations.AlterField(
            model_name='emailrecord',
            name='receiver',
            field=models.TextField(),
        ),
    ]
