# Generated by Django 5.2.8 on 2025-11-06 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_sender', '0002_emailrecord_bcc_emailrecord_cc_emailrecord_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailrecord',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
