# Generated by Django 5.2.8 on 2025-11-12 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_sender', '0003_alter_emailrecord_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailrecord',
            name='filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
