# Generated by Django 5.2.8 on 2025-11-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_sender', '0004_emailrecord_filename'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
